name: card_matching_game
description: A Flutter card matching game

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/back.jpg
    - images/card1.jpg
    - images/card2.jpg
    - images/card3.jpg
    - images/card4.jpg
    - images/card5.jpg
    - images/card6.jpg
    - images/card7.jpg
    - images/card8.jpg
   